<?php

namespace ContainerUcYchce;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Nc_MfnrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Nc.mfnr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Nc.mfnr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\OrderController::delete' => ['privates', '.service_locator.Xe60xz3', 'get_ServiceLocator_Xe60xz3Service', true],
            'App\\Controller\\OrderController::edit' => ['privates', '.service_locator.Xe60xz3', 'get_ServiceLocator_Xe60xz3Service', true],
            'App\\Controller\\OrderController::find' => ['privates', '.service_locator.TRKRLFK', 'get_ServiceLocator_TRKRLFKService', true],
            'App\\Controller\\OrderController::index' => ['privates', '.service_locator.0Li1Ifw', 'get_ServiceLocator_0Li1IfwService', true],
            'App\\Controller\\OrderController::new' => ['privates', '.service_locator.TRKRLFK', 'get_ServiceLocator_TRKRLFKService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.ol3LFVu', 'get_ServiceLocator_Ol3LFVuService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.9uW928t', 'get_ServiceLocator_9uW928tService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\OrderController:delete' => ['privates', '.service_locator.Xe60xz3', 'get_ServiceLocator_Xe60xz3Service', true],
            'App\\Controller\\OrderController:edit' => ['privates', '.service_locator.Xe60xz3', 'get_ServiceLocator_Xe60xz3Service', true],
            'App\\Controller\\OrderController:find' => ['privates', '.service_locator.TRKRLFK', 'get_ServiceLocator_TRKRLFKService', true],
            'App\\Controller\\OrderController:index' => ['privates', '.service_locator.0Li1Ifw', 'get_ServiceLocator_0Li1IfwService', true],
            'App\\Controller\\OrderController:new' => ['privates', '.service_locator.TRKRLFK', 'get_ServiceLocator_TRKRLFKService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.ol3LFVu', 'get_ServiceLocator_Ol3LFVuService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.9uW928t', 'get_ServiceLocator_9uW928tService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\OrderController::delete' => '?',
            'App\\Controller\\OrderController::edit' => '?',
            'App\\Controller\\OrderController::find' => '?',
            'App\\Controller\\OrderController::index' => '?',
            'App\\Controller\\OrderController::new' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\OrderController:delete' => '?',
            'App\\Controller\\OrderController:edit' => '?',
            'App\\Controller\\OrderController:find' => '?',
            'App\\Controller\\OrderController:index' => '?',
            'App\\Controller\\OrderController:new' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
