<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Hydrator\HydratorException;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class AppDocumentOrderHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate(object $document, array $data, array $hints = array()): array
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['id']['type'];
                $return = $value instanceof \MongoDB\BSON\ObjectId ? (string) $value : $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['productName']) || (! empty($this->class->fieldMappings['productName']['nullable']) && array_key_exists('productName', $data))) {
            $value = $data['productName'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['productName']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['productName']->setValue($document, $return);
            $hydratedData['productName'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['userId']) || (! empty($this->class->fieldMappings['userId']['nullable']) && array_key_exists('userId', $data))) {
            $value = $data['userId'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['userId']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['userId']->setValue($document, $return);
            $hydratedData['userId'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['quantity']) || (! empty($this->class->fieldMappings['quantity']['nullable']) && array_key_exists('quantity', $data))) {
            $value = $data['quantity'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['quantity']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['quantity']->setValue($document, $return);
            $hydratedData['quantity'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['unitPrice']) || (! empty($this->class->fieldMappings['unitPrice']['nullable']) && array_key_exists('unitPrice', $data))) {
            $value = $data['unitPrice'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['unitPrice']['type'];
                $return = (float) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['unitPrice']->setValue($document, $return);
            $hydratedData['unitPrice'] = $return;
        }
        return $hydratedData;
    }
}