<?php

namespace ContainerJoaLb95;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Document\Order' shared autowired service.
     *
     * @return \App\Document\Order
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Document/Order.php';

        return $container->privates['App\\Document\\Order'] = new \App\Document\Order();
    }
}
