<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTIur5ni\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTIur5ni/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTIur5ni.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTIur5ni\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTIur5ni\App_KernelDevDebugContainer([
    'container.build_hash' => 'TIur5ni',
    'container.build_id' => 'dc8c32e2',
    'container.build_time' => 1661554857,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTIur5ni');
