<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container83DZWWG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container83DZWWG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container83DZWWG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container83DZWWG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container83DZWWG\App_KernelDevDebugContainer([
    'container.build_hash' => '83DZWWG',
    'container.build_id' => 'fdf22973',
    'container.build_time' => 1661539124,
], __DIR__.\DIRECTORY_SEPARATOR.'Container83DZWWG');
